// <auto-generated />
using System;
using MediView.Studies.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediView.Studies.Infrastructure.Migrations
{
    [DbContext(typeof(StudiesDbContext))]
    [Migration("20260922111631_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("studies")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("study_number_seq")
                .StartsAt(1000L);

            modelBuilder.Entity("MediView.Studies.Domain.Studies.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("doctor_name");

                    b.Property<DateTimeOffset?>("ImagesImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("images_imported_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PatientMrn")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("patient_mrn");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("patient_name");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("ScheduledStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StudyNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("study_number")
                        .HasDefaultValueSql("'STU-' || nextval('studies.study_number_seq')");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_studies");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_studies_patient_id");

                    b.HasIndex("StudyNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_studies_study_number");

                    b.HasIndex("DoctorId", "ScheduledStart")
                        .IsUnique()
                        .HasDatabaseName("ix_studies_doctor_id_scheduled_start");

                    b.ToTable("studies", "studies");
                });

            modelBuilder.Entity("MediView.Studies.Domain.Studies.Study", b =>
                {
                    b.OwnsMany("MediView.Studies.Domain.Studies.StudyStatusHistory", "History", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b1.Property<long>("Id"));

                            b1.Property<DateTimeOffset>("ChangedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("changed_at");

                            b1.Property<Guid>("ChangedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("changed_by");

                            b1.Property<string>("FromStatus")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("from_status");

                            b1.Property<string>("Reason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("reason");

                            b1.Property<Guid>("StudyId")
                                .HasColumnType("uuid")
                                .HasColumnName("study_id");

                            b1.Property<string>("ToStatus")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("to_status");

                            b1.HasKey("Id")
                                .HasName("pk_study_status_history");

                            b1.HasIndex("StudyId", "ChangedAt")
                                .HasDatabaseName("ix_study_status_history_study_id_changed_at");

                            b1.ToTable("study_status_history", "studies");

                            b1.WithOwner()
                                .HasForeignKey("StudyId")
                                .HasConstraintName("fk_study_status_history_studies_study_id");
                        });

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
