<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MediView.Reporting.Infrastructure\MediView.Reporting.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>30330461-fb30-4268-a5f6-1c195e111fb8</UserSecretsId>
  </PropertyGroup>

</Project>
