<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\MediView.BuildingBlocks.Application\MediView.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\MediView.Reporting.Domain\MediView.Reporting.Domain.csproj" />
  </ItemGroup>

</Project>
