// <auto-generated />
using System;
using MediView.Reporting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediView.Reporting.Infrastructure.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20260922113437_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediView.Reporting.Domain.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Decision")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("decision");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("doctor_name");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<string>("Findings")
                        .HasColumnType("text")
                        .HasColumnName("findings");

                    b.Property<string>("Impression")
                        .HasColumnType("text")
                        .HasColumnName("impression");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_reports_study_id");

                    b.HasIndex("DoctorId", "Status")
                        .HasDatabaseName("ix_reports_doctor_id_status");

                    b.ToTable("reports", "reporting");
                });

            modelBuilder.Entity("MediView.Reporting.Domain.Reports.Report", b =>
                {
                    b.OwnsMany("MediView.Reporting.Domain.Reports.ReportMedication", "Medications", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Dosage")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("dosage");

                            b1.Property<string>("DrugName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("drug_name");

                            b1.Property<string>("Duration")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("duration");

                            b1.Property<string>("Frequency")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("frequency");

                            b1.Property<Guid>("ReportId")
                                .HasColumnType("uuid")
                                .HasColumnName("report_id");

                            b1.HasKey("Id")
                                .HasName("pk_report_medications");

                            b1.HasIndex("ReportId")
                                .HasDatabaseName("ix_report_medications_report_id");

                            b1.ToTable("report_medications", "reporting");

                            b1.WithOwner()
                                .HasForeignKey("ReportId")
                                .HasConstraintName("fk_report_medications_reports_report_id");
                        });

                    b.Navigation("Medications");
                });
#pragma warning restore 612, 618
        }
    }
}
