<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\MediView.BuildingBlocks.Api\MediView.BuildingBlocks.Api.csproj" />
    <ProjectReference Include="..\MediView.Studies.Infrastructure\MediView.Studies.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <UserSecretsId>a6bcabbb-b3fb-458d-ab39-728fec76d06a</UserSecretsId>
  </PropertyGroup>

</Project>
