<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\MediView.BuildingBlocks.Application\MediView.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\MediView.Studies.Domain\MediView.Studies.Domain.csproj" />
  </ItemGroup>

</Project>
